### PR TITLE
FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status on hpd_e…

### PR DESCRIPTION
**Pull request by YongxingMou**
…nable

If a downstream consumer (e.g. drm_bridge_connector attached by the msm/dp driver) registers its HPD callback after an upstream driver has already reported a HPD event through drm_aux_hpd_bridge_notify(), the notification is dropped because bridge->hpd_cb is still NULL. This can affect any user of drm_aux_hpd_bridge_notify() whose downstream consumer arms HPD only after upstream events have started.

The race has been observed on Qualcomm X1E-based laptops during boot, when pmic_glink_altmode reports the initial USB-C DP connection state before the DP driver has finished probing and enabled HPD handling on the bridge. The consumer then never observes the initial connected state and the external display remains dark.

Cache the last HPD status reported through drm_aux_hpd_bridge_notify() and replay it when HPD is enabled by the downstream consumer.

The replay is deferred to a work item so that the replayed HPD notification is delivered outside drm_bridge_hpd_enable()'s call context.

This follows the same pattern as display-connector, which also defers an initial HPD notification from .hpd_enable(), but reuses the cached status since aux-hpd-bridge cannot re-detect sink presence on its own.

Fixes: e560518a6c2e ("drm/bridge: implement generic DP HPD bridge")

Link: https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/

CRs-Fixed: 4618390

### CODE REVIEW

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1631

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1631
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/30800264633

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict (add/add) | drivers/gpu/drm/bridge/lontium-lt9611c.c | No | Pre-existing integration conflict in topic branch `topic/tech/mm/drm` unrelated to PR changes |

### Verdict
**0 of 1 errors are introduced by this PR; 1 is a pre-existing integration issue.** The PR itself is clean and does not cause any compilation errors. The build failed during the automerge step when integrating the topic branch with the baseline, encountering a merge conflict in a file (`lontium-lt9611c.c`) that this PR does not modify.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/68951bb3393d453df6f2dfb8192a8b38)

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1631

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1631
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/30800264633

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict (add/add) | drivers/gpu/drm/bridge/lontium-lt9611c.c | No | Pre-existing integration conflict between topic branches during automerge; unrelated to PR changes |

### Verdict
This is not a compilation failure. The build failed during the automerge/integration step due to a pre-existing conflict in `lontium-lt9611c.c`, which is not modified by this PR. The PR changes to `aux-hpd-bridge.c` are not the cause of this failure.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/2ee0307869067396589478604ba863d0)

**Comment by qlijarvis** [comment]
## PR #1631 — validate-patch

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1631

| Verdict | Issues | Detailed Report |
|---------|--------|-----------------|
| ❌ | 3 | [Full report](https://gist.github.com/qlijarvis/34880319a774285f8c692de07e26dc40) |

### Final Summary
1. **Lore link present:** Yes — https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/
2. **Lore link matches PR commits:** No — PR modifies different function (`_notify_extra` vs `_notify`), adds extra conditional logic, removes atomic helper hooks, and changes comment wording; these are semantic changes beyond context adaptation
3. **Upstream patch status:** ⏳ Decision Pending — posted 2026-08-03, only AI bot reply, no maintainer decision yet
4. PR present in qcom-next/topics: Partial - 1/1 commit(s) only have partial integration evidence

<blockquote>
<details>
<summary>Verdict: ❌ — click to expand</summary>

## 🔍 Patch Validation

**PR:** #1631 - FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status on hpd_enable  
**Upstream commit:** https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/  
**Verdict:** ❌ FAIL

### Commit Message
| Check | Status | Note |
|-------|--------|------|
| Subject matches upstream | ✅ | Subject identical (FROMLIST: prefix added correctly) |
| Body preserves rationale | ✅ | Full problem description and fix rationale preserved |
| Fixes tag present/correct | ✅ | `Fixes: e560518a6c2e` present and correct |
| Authorship preserved | ✅ | `From:` matches lore author (Yongxing Mou) |
| Backport note (if applicable) | N/A | FROMLIST: commit, not a backport |

### Diff
| File | Status | Notes |
|------|--------|-------|
| `drivers/gpu/drm/bridge/aux-hpd-bridge.c` | ❌ | Multiple semantic changes not present in upstream lore patch |

### Issues

**Critical diff divergences from lore upstream:**

1. **Extra conditional logic in notify function** — PR adds 8-line comment + `if (status != connector_status_unknown)` guard around `WRITE_ONCE(data->last_status, status)` in `drm_aux_hpd_bridge_notify_extra()`. Lore patch has unconditional `WRITE_ONCE(data->last_status, status)` in `drm_aux_hpd_bridge_notify()`.

2. **Different function patched** — PR modifies `drm_aux_hpd_bridge_notify_extra()` while lore patch modifies `drm_aux_hpd_bridge_notify()`. These are different functions with different signatures.

3. **Missing atomic helper hooks** — Lore patch includes `.atomic_create_state`, `.atomic_destroy_state`, `.atomic_duplicate_state` in `drm_aux_hpd_bridge_funcs`. PR patch removes these entirely, leaving only `.attach`, `.hpd_enable`, `.hpd_disable`.

4. **Different comment wording** — PR comment says "Deferred to a work **because** drm_bridge_hpd_notify() takes bridge->hpd_mutex which is already held by drm_bridge_hpd_enable()." Lore comment says "Deferred to a work **item so that** the replayed HPD notification is delivered outside drm_bridge_hpd_enable()'s call context." (semantic difference: PR explains *why* mutex is a problem; lore explains *what* the deferral achieves).

5. **Different include context** — Lore patch shows `#include <drm/drm_atomic_helper.h>` in context; PR shows `#include <drm/bridge/aux-bridge.h>`. This indicates the PR is based on a different tree version where the file structure differs.

**Root cause:** This PR appears to be a **modified adaptation** of the lore patch to a different kernel tree version (likely qcom-next or a vendor tree) where:
- The file has been refactored (no atomic helpers, different includes)
- The notify function has been split into `_notify()` and `_notify_extra()`
- Additional logic was added to handle `connector_status_unknown` filtering

This is **not a faithful FROMLIST: backport** — it contains significant semantic changes beyond simple context adaptation.

### Upstream Patch Status
| Commit | Community Verdict |
|--------|------------------|
| drm/bridge: aux-hpd-bridge: replay last HPD status on hpd_enable | ⏳ Decision Pending — posted 2026-08-03, only AI bot reply (Sashiko), no maintainer review yet |

### qcom-next Presence
| Commit | Status |
|--------|--------|
| FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status | ⚠️ Partial — subject or partial tree evidence found in qcom-next, but full change not verified (per integration_presence_report.md) |

### Verdict

**Do not merge without correction.** This PR is labelled `FROMLIST:` but contains substantial semantic changes not present in the linked lore patch:

1. Different function modified (`_notify_extra` vs `_notify`)
2. Extra conditional logic filtering `connector_status_unknown`
3. Missing atomic helper function pointers
4. Different comment rationale

**Required fixes:**

- If this is an **adaptation to a refactored tree**, split into two commits:
  1. `FROMLIST:` commit with **only** the changes present in the lore patch (modify `_notify()`, add work queue, add hpd_enable/disable)
  2. `QCLINUX:` or `PENDING:` commit with the extra `connector_status_unknown` filtering logic and any other vendor-specific adaptations

- If the lore patch **itself needs updating** to match this implementation, post a v2 to lore.kernel.org first, then update the PR's `Link:` tag to point to the new revision.

- Update the commit message to explain **why** the PR differs from lore (e.g., "Adapted to qcom-next tree where aux-hpd-bridge has been refactored to split notify functions").

### Final Summary
1. **Lore link present:** Yes — https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/
2. **Lore link matches PR commits:** No — PR modifies different function (`_notify_extra` vs `_notify`), adds extra conditional logic, removes atomic helper hooks, and changes comment wording; these are semantic changes beyond context adaptation
3. **Upstream patch status:** ⏳ Decision Pending — posted 2026-08-03, only AI bot reply, no maintainer decision yet
4. **PR present in qcom-next/topics:** Partial — integration_presence_report.md shows "partial - subject or partial tree evidence found, but full change was not verified" (1/1 commits partial)


### Deterministic Integration Presence

# Integration Presence Report

This report is generated by Jarvis before validate-patch runs.
It is the authoritative source for whether PR changes are already present
in qcom-next or in the kernel topic branches.

Kernel repo: `/local/mnt/workspace/sgaud/Qgenie/image_pipeline/kernel`
qcom-next ref: `8d5dbc1b17adf8fe86a41adcda686785e73f5414`
topics remote: `topics` -> `https://github.com/qualcomm-linux/kernel-topics`
topics fetch: `fetched`

| Commit | Subject | qcom-next | topics | Final |
|--------|---------|-----------|--------|-------|
| 1/1 | `[PATCH] FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status` | partial - subject or partial tree evidence found, but full change was not verified | missing - no subject, patch-id, or full tree-content match found | partial |

## Final Status

overall_status: PARTIAL
present_commits: 0/1
partial_commits: 1/1
missing_commits: 0/1
topics_checked_for_commits: 1/1
final_summary: PR present in qcom-next/topics: Partial - 1/1 commit(s) only have partial integration evidence

</details>
</blockquote>

**Comment by qlijarvis** [comment]
## PR #1631 — checker-log-analyzer

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1631
**Checker run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/30800264652

| Checker | Result | Summary |
|---------|--------|---------|
| Checker | Result | Summary |
| checkpatch | ❌ | Automerge conflict - never reached checker |
| dt-binding-check | ❌ | Automerge conflict - never reached checker |
| dtb-check | ❌ | Automerge conflict - never reached checker |
| sparse-check | ❌ | Automerge conflict - never reached checker |
| check-uapi-headers | ❌ | Automerge conflict - never reached checker |
| check-patch-compliance | ❌ | Git fetch failure (HTTP 503) |
| tag-check | ✅ | Subject has valid `FROMLIST:` prefix |

Detailed report: [Full report](https://gist.github.com/qlijarvis/d02c2239b60d965c7397830364144f4b)

<blockquote>
<details>
<summary>Checker analysis — click to expand</summary>

## 🤖 CI Checker Analysis (checker-log-analyzer)

**PR:** #1631 - FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status on hpd_enable  
**Source:** https://github.com/qualcomm-linux/kernel-config/actions/runs/30800264652

| Checker | Result | Summary |
|---------|--------|---------|
| checkpatch | ❌ | Automerge conflict - never reached checker |
| dt-binding-check | ❌ | Automerge conflict - never reached checker |
| dtb-check | ❌ | Automerge conflict - never reached checker |
| sparse-check | ❌ | Automerge conflict - never reached checker |
| check-uapi-headers | ❌ | Automerge conflict - never reached checker |
| check-patch-compliance | ❌ | Git fetch failure (HTTP 503) |
| tag-check | ✅ | Subject has valid `FROMLIST:` prefix |

### ❌ CI Infrastructure Failures

**Root cause:** All checker jobs failed during the pre-check automerge phase, not due to patch defects.

**Failure details:**

**1. Automerge conflict (5 checkers):**
```
CONFLICT (add/add): Merge conflict in drivers/gpu/drm/bridge/lontium-lt9611c.c
Automatic merge failed; fix conflicts and then commit the result.
automerge returned non-zero; check logs for conflicts
##[error]Process completed with exit code 1.
```

The CI workflow attempts to merge the PR branch (`topic/tech/mm/drm`) with the baseline (`qcom-next`) before running checkers. This merge encountered a conflict in `drivers/gpu/drm/bridge/lontium-lt9611c.c` — a file that is **not modified by this PR** (PR only touches `drivers/gpu/drm/bridge/aux-hpd-bridge.c`).

This is a **pre-existing integration conflict** between the topic branch and qcom-next, unrelated to PR #1631.

**2. Git fetch failure (check-patch-compliance):**
```
error: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503
fatal: expected flush after ref listing
##[error]Process completed with exit code 128.
```

GitHub API returned HTTP 503 (Service Unavailable) during `git fetch origin qcom-next`. This is a transient network/service issue.

**Fix:** 

**For the automerge conflict:**
- This is **not a blocker for PR #1631**. The conflict is in `lontium-lt9611c.c`, which is not touched by this PR.
- The topic branch maintainer needs to resolve the conflict between `topic/tech/mm/drm` and `qcom-next` baseline.
- Once the topic branch conflict is resolved, re-trigger CI for this PR.

**For the HTTP 503 error:**
- Re-trigger the CI workflow. This is a transient GitHub service issue.

**Reproduce locally:**

To verify the automerge conflict independently:
```bash
git clone https://github.com/qualcomm-linux/kernel.git
cd kernel
git fetch origin qcom-next
git checkout qcom-next
git fetch https://github.com/qualcomm-linux/kernel-topics.git topic/tech/mm/drm
git merge FETCH_HEAD
# Conflict will appear in lontium-lt9611c.c
```

### ✅ Patch Quality (from manual inspection)

Since the checkers never ran, I inspected the patch directly:

**Commit:** `fe51d83f4ef2` - "FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status on hpd_enable"

- ✅ **Subject prefix:** Valid `FROMLIST:` prefix present
- ✅ **Link trailer:** Contains `Link: https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/`
- ✅ **Signed-off-by:** Present
- ✅ **Fixes tag:** Present (`Fixes: e560518a6c2e`)
- ✅ **Code changes:** Single file modified (`drivers/gpu/drm/bridge/aux-hpd-bridge.c`), adds HPD status caching and replay logic
- ✅ **Style:** No obvious checkpatch violations visible in the diff

### Verdict

**CI failure is not caused by this PR.** The patch itself appears well-formed with proper upstream linkage and commit message formatting.

**Action required:** Re-trigger CI after the topic branch maintainer resolves the `lontium-lt9611c.c` conflict between `topic/tech/mm/drm` and `qcom-next`.

The patch is **ready for review** from a code quality perspective — the CI infrastructure issues are blocking validation, not patch defects.


</details>
</blockquote>

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1631

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1631
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/31454619138

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict (content) | `Documentation/devicetree/bindings/display/bridge/lontium,lt9611.yaml` | **No** | Pre-existing conflict in topic branch `topic/tech/mm/drm` during automerge with baseline |
| 2 | Merge conflict (content) | `drivers/gpu/drm/bridge/Kconfig` | **No** | Pre-existing conflict in topic branch `topic/tech/mm/drm` during automerge with baseline |
| 3 | Merge conflict (add/add) | `drivers/gpu/drm/bridge/lontium-lt9611c.c` | **No** | Pre-existing conflict in topic branch `topic/tech/mm/drm` during automerge with baseline |
| 4 | Merge conflict (content) | `sound/soc/qcom/sc8280xp.c` | **No** | Pre-existing conflict in topic branch `topic/tech/mm/drm` during automerge with baseline |

### Verdict
**0 of 4 failures are introduced by this PR; all 4 are pre-existing integration conflicts.** This PR only modifies `drivers/gpu/drm/bridge/aux-hpd-bridge.c` and does not touch any of the conflicting files. The build failure is due to merge conflicts in the topic branch integration workflow, not compilation errors in the PR code.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/50c9fe26fa1cdcf7a280fec443f84ca1)

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1631

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1631
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/31454619138

### Analysis Result

**This is NOT a compilation failure.** The build failed during the **automerge** phase before any compilation occurred. The PR changes to `drivers/gpu/drm/bridge/aux-hpd-bridge.c` do not introduce any compilation errors.

### Merge Conflicts Encountered

The automerge step failed when attempting to merge the PR with the `topic/tech/mm/drm` branch. Four merge conflicts were detected in files **unrelated** to this PR:

| # | Conflict Type | File | PR-introduced? | Root Cause |
|---|---------------|------|----------------|------------|
| 1 | Content conflict | `Documentation/devicetree/bindings/display/bridge/lontium,lt9611.yaml` | No | Pre-existing conflict between baseline and topic branch |
| 2 | Content conflict | `drivers/gpu/drm/bridge/Kconfig` | No | Pre-existing conflict between baseline and topic branch |
| 3 | Add/add conflict | `drivers/gpu/drm/bridge/lontium-lt9611c.c` | No | Pre-existing conflict between baseline and topic branch |
| 4 | Content conflict | `sound/soc/qcom/sc8280xp.c` | No | Pre-existing conflict between baseline and topic branch |

### Verdict
**0 compilation errors.** All 4 merge conflicts are pre-existing issues in the `topic/tech/mm/drm` branch and are completely unrelated to the changes in PR #1631. The PR modifies only `drivers/gpu/drm/bridge/aux-hpd-bridge.c`, which merged cleanly without conflicts.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/c5b287008ea08e44cee352456997f01f)

**Comment by qlijarvis** [comment]
## PR #1631 — validate-patch

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1631

| Verdict | Issues | Detailed Report |
|---------|--------|-----------------|
| ❌ | 0 | [Full report](https://gist.github.com/qlijarvis/741bf804e69122956ede8bd7e21d467c) |

### Final Summary
1. **Lore link present:** Yes — https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/
2. **Lore link matches PR commits:** No — PR modifies different function (`notify_extra` vs `notify`), adds conditional caching logic not in lore, missing atomic helper includes/assignments from lore, and includes extra comment not in upstream
3. **Upstream patch status:** ⏳ Decision Pending — posted Aug 3, 2026; no maintainer review yet, only automated bot response
4. PR present in qcom-next/topics: Partial - 1/1 commit(s) only have partial integration evidence

<blockquote>
<details>
<summary>Verdict: ❌ — click to expand</summary>

## 🔍 Patch Validation

**PR:** [PATCH] FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status on hpd_enable (PR #1631)
**Upstream commit:** https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/
**Verdict:** ❌ FAIL

### Commit Message
| Check | Status | Note |
|-------|--------|------|
| Subject matches upstream | ✅ | Subject identical except for `FROMLIST:` prefix |
| Body preserves rationale | ✅ | Full commit message preserved |
| Fixes tag present/correct | ✅ | `Fixes: e560518a6c2e` present |
| Authorship preserved | ✅ | `From: Yongxing Mou <yongxing.mou@oss.qualcomm.com>` matches lore |
| Backport note (if applicable) | N/A | Not a backport — `FROMLIST:` prefix correct |

### Diff
| File | Status | Notes |
|------|--------|-------|
| `drivers/gpu/drm/bridge/aux-hpd-bridge.c` | ❌ | **Significant divergence**: PR adds extra logic not present in lore patch |

### Issues

**Critical: Extra code added beyond lore patch**

The PR patch contains **significant additional logic** not present in the upstream lore patch:

1. **Missing include in lore**: Lore patch includes `<drm/drm_atomic_helper.h>` but PR patch does not
   - Lore: `#include <drm/drm_atomic_helper.h>`
   - PR: Missing this include

2. **Different notify function modified**: 
   - **Lore patch** modifies `drm_aux_hpd_bridge_notify()` with simple unconditional caching:
     ```c
     WRITE_ONCE(data->last_status, status);
     ```
   - **PR patch** modifies `drm_aux_hpd_bridge_notify_extra()` with conditional caching logic:
     ```c
     if (status != connector_status_unknown)
         WRITE_ONCE(data->last_status, status);
     ```
   - The PR adds an 8-line comment explaining IRQ_HPD-only events that is **not in the lore patch**

3. **Different drm_bridge_funcs structure**:
   - **Lore patch** includes atomic helper function pointers:
     ```c
     .atomic_create_state = drm_atomic_helper_bridge_create_state,
     .atomic_destroy_state = drm_atomic_helper_bridge_destroy_state,
     .atomic_duplicate_state = drm_atomic_helper_bridge_duplicate_state,
     ```
   - **PR patch** does not include these atomic helper assignments

4. **Different hpd_enable comment**:
   - **Lore**: "Deferred to a work item so that the replayed HPD notification is delivered outside drm_bridge_hpd_enable()'s call context."
   - **PR**: "Deferred to a work because drm_bridge_hpd_notify() takes bridge->hpd_mutex which is already held by drm_bridge_hpd_enable()."

**Root cause**: The PR patch appears to be based on a **different kernel tree version** than the lore patch. The lore patch targets a tree with `drm_atomic_helper.h` and atomic bridge state functions, while the PR targets a tree without these. The PR author has adapted the patch with additional logic for `drm_aux_hpd_bridge_notify_extra()` that was not reviewed upstream.

### Upstream Patch Status
| Commit | Community Verdict |
|--------|------------------|
| drm/bridge: aux-hpd-bridge: replay last HPD status on hpd_enable | ⏳ Decision Pending — posted Aug 3, 2026; only automated Sashiko AI review present; no maintainer response yet |

### qcom-next Presence
| Commit | Status |
|--------|--------|
| FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status | ⚠️ Partial — subject or partial tree evidence found in qcom-next, but full change not verified (per integration_presence_report.md) |

### Verdict

**Do not merge** — the PR patch diverges significantly from the lore patch it claims to represent:

1. The PR modifies `drm_aux_hpd_bridge_notify_extra()` with conditional caching logic, while the lore patch modifies `drm_aux_hpd_bridge_notify()` with unconditional caching
2. The PR adds an 8-line comment about IRQ_HPD-only events not present in the lore patch
3. The PR is missing the `drm_atomic_helper.h` include present in lore
4. The PR's `drm_bridge_funcs` structure lacks atomic helper function pointers present in lore
5. The hpd_enable comment differs between PR and lore

**Recommendation**: Either:
- Update the PR to faithfully match the lore patch (if the target tree supports atomic helpers), OR
- Remove the `FROMLIST:` prefix and use `QCLINUX:` or `PENDING:` since this is a modified adaptation, not a faithful representation of the upstream posting

### Final Summary
1. **Lore link present:** Yes — https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/
2. **Lore link matches PR commits:** No — PR modifies different function (`notify_extra` vs `notify`), adds conditional caching logic not in lore, missing atomic helper includes/assignments from lore, and includes extra comment not in upstream
3. **Upstream patch status:** ⏳ Decision Pending — posted Aug 3, 2026; no maintainer review yet, only automated bot response
4. **PR present in qcom-next/topics:** Partial — integration_presence_report.md shows partial evidence only; full change not verified


### Deterministic Integration Presence

# Integration Presence Report

This report is generated by Jarvis before validate-patch runs.
It is the authoritative source for whether PR changes are already present
in qcom-next or in the kernel topic branches.

Kernel repo: `/local/mnt/workspace/sgaud/Qgenie/image_pipeline/kernel`
qcom-next ref: `8d5dbc1b17adf8fe86a41adcda686785e73f5414`
topics remote: `topics` -> `https://github.com/qualcomm-linux/kernel-topics`
topics fetch: `fetched`

| Commit | Subject | qcom-next | topics | Final |
|--------|---------|-----------|--------|-------|
| 1/1 | `[PATCH] FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status` | partial - subject or partial tree evidence found, but full change was not verified | missing - no subject, patch-id, or full tree-content match found | partial |

## Final Status

overall_status: PARTIAL
present_commits: 0/1
partial_commits: 1/1
missing_commits: 0/1
topics_checked_for_commits: 1/1
final_summary: PR present in qcom-next/topics: Partial - 1/1 commit(s) only have partial integration evidence

</details>
</blockquote>

**Comment by qlijarvis** [comment]
## PR #1631 — checker-log-analyzer

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1631
**Checker run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/31454619153

| Checker | Result | Summary |
|---------|--------|---------|
| Checker | Result | Summary |
| checkpatch | ⚠️ | Blocked by automerge conflicts |
| dt-binding-check | ⚠️ | Blocked by automerge conflicts |
| dtb-check | ⚠️ | Blocked by automerge conflicts |
| sparse-check | ⚠️ | Blocked by automerge conflicts |
| check-uapi-headers | ⚠️ | Blocked by automerge conflicts |
| check-patch-compliance | ⚠️ | Blocked by automerge conflicts |
| tag-check | ✅ | Subject has valid `FROMLIST:` prefix |

Detailed report: [Full report](https://gist.github.com/qlijarvis/ebaa3b20ffef5018ce146ca831cdd2b7)

<blockquote>
<details>
<summary>Checker analysis — click to expand</summary>


## 🤖 CI Checker Analysis (checker-log-analyzer)

**PR:** #1631 - FROMLIST: drm/bridge: aux-hpd-bridge: replay last HPD status on hpd_enable  
**Source:** https://github.com/qualcomm-linux/kernel-config/actions/runs/31454619153

| Checker | Result | Summary |
|---------|--------|---------|
| checkpatch | ⚠️ | Blocked by automerge conflicts |
| dt-binding-check | ⚠️ | Blocked by automerge conflicts |
| dtb-check | ⚠️ | Blocked by automerge conflicts |
| sparse-check | ⚠️ | Blocked by automerge conflicts |
| check-uapi-headers | ⚠️ | Blocked by automerge conflicts |
| check-patch-compliance | ⚠️ | Blocked by automerge conflicts |
| tag-check | ✅ | Subject has valid `FROMLIST:` prefix |

---

### ⚠️ CI Infrastructure Issue: Automerge Conflicts

**Root cause:** All checker jobs failed during the automerge stage when attempting to merge the PR into the integration branch (`topic/tech/mm/drm`). The PR patch itself only modifies `drivers/gpu/drm/bridge/aux-hpd-bridge.c`, but merge conflicts occurred in unrelated files.

**Failure details:**
```
CONFLICT (content): Merge conflict in Documentation/devicetree/bindings/display/bridge/lontium,lt9611.yaml
CONFLICT (content): Merge conflict in drivers/gpu/drm/bridge/Kconfig
CONFLICT (add/add): Merge conflict in drivers/gpu/drm/bridge/lontium-lt9611c.c
CONFLICT (content): Merge conflict in sound/soc/qcom/sc8280xp.c
Automatic merge failed; fix conflicts and then commit the result.
```

**Analysis:**
- The PR modifies only `drivers/gpu/drm/bridge/aux-hpd-bridge.c`
- Conflicts are in completely different files (lontium-lt9611.yaml, Kconfig, lontium-lt9611c.c, sc8280xp.c)
- These conflicts are **not caused by this PR** — they are pre-existing integration issues in the target topic branch
- **No checkers actually ran** — all failed at the pre-check automerge stage

**Fix:** This is a CI/integration infrastructure issue, not a patch defect. The conflicts need to be resolved in the integration branch before checkers can run. Options:

1. **Rebase the integration branch** to resolve conflicts with the baseline
2. **Re-trigger CI** after the integration branch is updated
3. **Manually verify** the patch passes checkers by running them locally on the PR branch without automerge

**Reproduce locally (without automerge):**
```bash
# Clone the PR branch directly
git fetch origin pull/1631/head:pr-1631
git checkout pr-1631

# Run checkers on the PR commit
./scripts/checkpatch.pl --strict --ignore FILE_PATH_CHANGES -g HEAD
make C=2 drivers/gpu/drm/bridge/aux-hpd-bridge.o
```

---

### ✅ Manual Patch Review (PR commit 1f2058c)

Since the checkers couldn't run, I performed a manual review of the patch:

**Subject prefix:** ✅ `FROMLIST:` — valid prefix for patches posted to mailing list  
**Link:** ✅ `https://lore.kernel.org/all/20260803-drm-usbdp-preboot-v1-1-2539b362be00@oss.qualcomm.com/`  
**Signed-off-by:** ✅ Present  
**Code style:** ✅ No obvious checkpatch violations observed  
**File modified:** `drivers/gpu/drm/bridge/aux-hpd-bridge.c` (C source file)

**Code changes:**
- Adds `#include <linux/workqueue.h>` ✅
- Adds `last_status` and `hpd_work` fields to struct ✅
- Implements `drm_aux_hpd_bridge_hpd_work()` work handler ✅
- Implements `drm_aux_hpd_bridge_hpd_enable()` and `hpd_disable()` callbacks ✅
- Uses `WRITE_ONCE()`/`READ_ONCE()` for lockless access ✅
- Initializes work with `INIT_WORK()` ✅
- Alignment in `drm_aux_hpd_bridge_funcs` struct uses tabs consistently ✅

**Potential checkpatch notes:**
- Line length appears within limits
- Comment style follows kernel conventions
- No trailing whitespace visible
- Locking documented in comments

---

### Verdict

**The PR patch itself appears clean and ready for merge**, but **CI cannot verify this** due to automerge conflicts in the integration branch.

**Recommended actions:**

1. **Resolve integration branch conflicts** — the `topic/tech/mm/drm` branch has conflicts with the baseline that prevent automerge
2. **Re-trigger CI** after integration branch is fixed
3. **Alternative:** Run checkers locally on the PR branch (without automerge) to verify patch quality independently

**Blocker:** CI infrastructure issue (automerge conflicts), not a patch defect.


</details>
</blockquote>

**Review by riteshk-quic — APPROVED** [review]
