### PR TITLE
Test CI/CD checks

### PR DESCRIPTION
**Pull request by imrashai**
This change is to test the CI/CD.

### CODE REVIEW

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1479

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1479
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28852861181

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| N/A | Merge conflict during automerge | Multiple files (101 conflicts) | No | Pre-existing integration conflicts between topic branches |

### Verdict
**This PR does not introduce any build errors.** The build failure occurred during the automerge/integration phase where multiple topic branches are merged together. The PR file `drivers/clk/qcom/common.c` merged cleanly without conflicts. All 101 merge conflicts are in unrelated files and are pre-existing integration issues between other topic branches, not caused by this PR.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/5b04f36c38e251b985637a319a92c6d7)

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1479

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1479
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28852861181

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| N/A | Merge conflict during automerge | Multiple files (108 conflicts) | No | Pre-existing conflicts in integration branch |

### Verdict
No compilation errors occurred. The build failed during the automerge phase due to 108 merge conflicts across multiple files. The PR changes to `drivers/clk/qcom/common.c` were successfully auto-merged and are not responsible for the failure.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/edba2955fc2802d6d7e4c49869e09eab)

**Comment by qlijarvis** [comment]
## PR #1479 — validate-patch

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1479

| Verdict | Issues | Detailed Report |
|---------|--------|-----------------|
| ❌ | 0 | [Full report](https://gist.github.com/qlijarvis/76b70bb6b5a75b99538fc2231b082103) |

### Final Summary
1. **Lore link present:** No — no lore.kernel.org link found in commit message
2. **Lore link matches PR commits:** N/A — no lore link to compare against
3. **Upstream patch status:** Unknown — cannot determine without lore link
4. **PR present in qcom-next:** Not checked — validation cannot proceed without lore link

<blockquote>
<details>
<summary>Verdict: ❌ — click to expand</summary>

## Patch Validation Report

**PR:** clk: qcom: common: Register reset controller only when resets are present (#1479)  
**Upstream:** (none found)  
**Verdict:** ❌ FAIL

### Reason
No lore.kernel.org link was found in the PR description or commit message(s).
This skill only validates patches against a lore.kernel.org source.

### Recommendation
Add a `Link: https://lore.kernel.org/r/<message-id>` line to the commit message and re-run validation, or use an appropriate prefix:
- `UPSTREAM:` → link to the merged kernel.org commit (not applicable here)
- `FROMLIST:` → link to the lore.kernel.org posting
- `BACKPORT:` → link to the original lore.kernel.org or upstream commit
- `QCLINUX:` → vendor-only change, no upstream link expected
- `PENDING:` → work-in-progress, not yet posted upstream
- `WORKAROUND:` → temporary fix, not suitable for upstream

Commits with `QCLINUX:`, `PENDING:`, or `WORKAROUND:` prefixes have no upstream lore link by design and cannot be validated with this skill.

### Final Summary
1. **Lore link present:** No — no lore.kernel.org link found in commit message
2. **Lore link matches PR commits:** N/A — no lore link to compare against
3. **Upstream patch status:** Unknown — cannot determine without lore link
4. **PR present in qcom-next:** Not checked — validation cannot proceed without lore link

### Additional Notes
The patch modifies `drivers/clk/qcom/common.c` to conditionally register the reset controller only when `desc->num_resets` is non-zero. This appears to be a reasonable fix for clock controllers that don't provide reset lines, but without a lore link or vendor prefix, it's unclear whether this is:
- An upstream patch that should have a `FROMLIST:` or `UPSTREAM:` prefix with a lore link
- A vendor-specific change that should have a `QCLINUX:` prefix
- A work-in-progress that should have a `PENDING:` prefix

The commit author (`imran.shaik@oss.qualcomm.com`) and the nature of the change suggest this may be intended for upstream submission. If so, it should either:
1. Be posted to the linux-clk mailing list first, then prefixed with `FROMLIST:` and include the lore link
2. If already posted, add the appropriate prefix and lore link to the commit message

</details>
</blockquote>

**Comment by qlijarvis** [comment]
## PR #1479 — checker-log-analyzer

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1479
**Checker run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28852861459

| Checker | Result | Summary |
|---------|--------|---------|
| Checker | Result | Summary |
| checkpatch | ⏭️ | CI infrastructure failure - no checker execution |
| dt-binding-check | ⏭️ | CI infrastructure failure - no checker execution |
| dtb-check | ⏭️ | CI infrastructure failure - no checker execution |
| sparse-check | ⏭️ | CI infrastructure failure - no checker execution |
| check-uapi-headers | ⏭️ | CI infrastructure failure - no checker execution |
| check-patch-compliance | ⏭️ | CI infrastructure failure - no checker execution |
| tag-check | N/A | Cannot execute - CI failed before PR merge |

Detailed report: [Full report](https://gist.github.com/qlijarvis/80fe6945c1482a988deb6e8bebff80bd)

<blockquote>
<details>
<summary>Checker analysis — click to expand</summary>

## 🤖 CI Checker Analysis (checker-log-analyzer)

**PR:** #1479 - clk: qcom: common: Register reset controller only when resets are present  
**Source:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28852861459

| Checker | Result | Summary |
|---------|--------|---------|
| checkpatch | ⏭️ | CI infrastructure failure - no checker execution |
| dt-binding-check | ⏭️ | CI infrastructure failure - no checker execution |
| dtb-check | ⏭️ | CI infrastructure failure - no checker execution |
| sparse-check | ⏭️ | CI infrastructure failure - no checker execution |
| check-uapi-headers | ⏭️ | CI infrastructure failure - no checker execution |
| check-patch-compliance | ⏭️ | CI infrastructure failure - no checker execution |
| tag-check | N/A | Cannot execute - CI failed before PR merge |

---

### ❌ CI Infrastructure Failure

**Root cause:** The kernel-checkers CI workflow failed during the integration branch setup phase with `fatal: refusing to merge unrelated histories` when attempting to merge the topic branch `topic/tech/bsp/clk` into the baseline.

**Failure details:**
```
2026-07-07T08:51:32.2347744Z Create a new integration branch based on 19b282f417584cfe14ce6a262122c51553d026ec
2026-07-07T08:51:32.3957460Z Switched to a new branch 'integ'
2026-07-07T08:51:32.4024195Z Merging topic branches...
2026-07-07T08:51:32.4253625Z ------------------------------------------
2026-07-07T08:51:32.4254118Z  ** Merging topic branch: topic/tech/bsp/clk
2026-07-07T08:51:50.6178685Z fatal: refusing to merge unrelated histories
2026-07-07T08:51:50.7253717Z Merge failed, manual merge
[...]
2026-07-07T08:51:51.7172907Z Merging pr-1479 (no-commit)...
2026-07-07T08:52:11.2817360Z fatal: refusing to merge unrelated histories
2026-07-07T08:52:11.3910442Z Merge failed or conflicts detected. Aborting merge.
2026-07-07T08:52:11.3949897Z ##[error]Process completed with exit code 3.
```

All six checker jobs (`checkpatch`, `dt-binding-check`, `dtb-check`, `sparse-check`, `check-uapi-headers`, `check-patch-compliance`) failed with identical errors during the merge setup phase, before any actual checker validation could run.

**Analysis:**

This is a **CI configuration/infrastructure issue**, not a defect in the PR code itself. The error occurs because:

1. The CI workflow attempts to create an integration branch from baseline tag `19b282f417584cfe14ce6a262122c51553d026ec` (appears to be a `qcom-next` baseline)
2. It then tries to merge the topic branch `tech/bsp/clk` from `qualcomm-linux/kernel-topics`
3. The topic branch has no common ancestor (unrelated git history) with the baseline tag
4. Git refuses to merge unrelated histories without the `--allow-unrelated-histories` flag

**Root cause classification:**

This PR targets the `tech/bsp/clk` branch, which appears to be a standalone topic branch that was created independently (possibly rebased or recreated) and does not share git history with the `qcom-next` baseline that the CI is using for integration testing.

**Fix options:**

1. **For the PR author:** No action needed on the patch itself. The code change is straightforward and appears correct (adds a conditional check before registering reset controller).

2. **For the CI/repo maintainers:**
   - Option A: Update the CI workflow configuration to use `--allow-unrelated-histories` when merging topic branches that are known to have independent histories
   - Option B: Rebase the `tech/bsp/clk` branch onto the baseline to establish a common ancestor
   - Option C: Adjust the CI workflow to skip integration testing for topic branches and only validate the PR commits directly
   - Option D: Configure the workflow to use the topic branch tip as the baseline instead of `qcom-next` when the PR targets a topic branch

**Reproduce locally:**
```bash
# This will reproduce the CI failure:
git clone https://github.com/qualcomm-linux/kernel.git
cd kernel
git fetch https://github.com/qualcomm-linux/kernel.git refs/tags/qcom-next
git checkout -b integ 19b282f417584cfe14ce6a262122c51553d026ec
git fetch https://github.com/qualcomm-linux/kernel-topics.git tech/bsp/clk:topic/tech/bsp/clk
git merge topic/tech/bsp/clk
# Will fail with: fatal: refusing to merge unrelated histories

# To allow the merge (workaround):
git merge --allow-unrelated-histories topic/tech/bsp/clk
```

---

### 📋 Patch Content Review (Manual)

Since the checkers could not run, here's a manual review of the PR patch:

**Commit:** `8ed634ebe80663d99248934f1275d23921ba780c`  
**Subject:** `clk: qcom: common: Register reset controller only when resets are present`

**Code change:** The patch adds a conditional check `if (desc->num_resets)` before registering the reset controller in `qcom_cc_really_probe()`. This prevents unnecessary reset controller registration when a clock controller descriptor has no reset lines.

**Observations:**
- ✅ Code logic is sound and follows defensive programming practices
- ✅ Indentation and formatting appear correct
- ✅ Has `Signed-off-by:` trailer
- ⚠️ **Missing subject prefix** - The commit subject does not start with a required prefix (`FROMLIST:`, `FROMGIT:`, `UPSTREAM:`, `BACKPORT:`, `QCLINUX:`, `PENDING:`, or `WORKAROUND:`)
- ⚠️ **No Link: trailer** - If this patch was posted upstream or is based on an upstream patch, it should include a `Link:` trailer pointing to the lore.kernel.org URL

**Predicted checker results if CI had run:**

- `checkpatch`: Likely **PASS** (code formatting looks clean)
- `dt-binding-check`: **SKIP** (no DT binding changes)
- `dtb-check`: **SKIP** (no DTS changes)
- `sparse-check`: **SKIP** (no changes to files that would trigger sparse)
- `check-uapi-headers`: **SKIP** (no UAPI header changes)
- `check-patch-compliance`: Likely **FAIL** - missing subject prefix and missing `Link:` trailer
- `tag-check`: **FAIL** (if target branch is not `qcom-next`/`qcom-next-staging`) - subject must start with a valid prefix

---

### Verdict

**CI infrastructure issue blocks validation. The PR code itself appears correct, but compliance issues need addressing:**

1. **Blocker:** CI configuration must be fixed to allow checker execution
2. **Blocker (if not targeting qcom-next/qcom-next-staging):** Add required subject prefix (e.g., `FROMLIST:`, `UPSTREAM:`, or `QCLINUX:`)
3. **Recommended:** Add `Link:` trailer if this patch has an upstream equivalent or was posted to a mailing list

**Recommended actions:**
- **Immediate:** Re-trigger CI after fixing the topic branch history issue (maintainer action)
- **Before merge:** Update commit message with appropriate prefix and Link trailer (author action)


</details>
</blockquote>

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1479

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1479
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28857370181

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| N/A | Merge conflict (not compilation error) | Multiple files | No | Pre-existing integration conflicts between `tech/bsp/clk` branch and `qcom-next` baseline |

### Verdict
**No compilation errors exist.** The build failed during the automerge phase with 100+ merge conflicts in files completely unrelated to this PR. The PR changes to `drivers/clk/qcom/gcc-qcm2290.c` are not involved in any conflicts and would compile cleanly if the merge conflicts were resolved.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/7448cafe2178004a4f3ec35f0b0a8727)

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1479

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1479
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28857370181

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| N/A | Merge conflict (not compilation error) | Multiple files | No | Automerge failure between topic branches unrelated to PR changes |

### Verdict
This is NOT a compilation failure. The build failed during the automerge stage due to merge conflicts between topic branches. The PR modifies only `drivers/clk/qcom/gcc-qcm2290.c`, which is NOT among the conflicting files. **Zero compilation errors are introduced by this PR** — the build never reached the compilation stage.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/c6d755ea9b54040b960f42b444301caf)

**Comment by qlijarvis** [comment]
## PR #1479 — validate-patch

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1479

| Verdict | Issues | Detailed Report |
|---------|--------|-----------------|
| ❌ | 0 | [Full report](https://gist.github.com/qlijarvis/db5b74410d290f966e11fac650913f77) |

### Final Summary
1. **Lore link present:** No — no lore.kernel.org link found in commit message
2. **Lore link matches PR commits:** N/A — no lore link to compare against
3. **Upstream patch status:** Unknown — cannot determine without lore link or vendor prefix
4. **PR present in qcom-next:** Not checked — filesystem permission restrictions prevented qcom-next clone/search

<blockquote>
<details>
<summary>Verdict: ❌ — click to expand</summary>

## Patch Validation Report

**PR:**      #1479 - clk: qcom: gcc-qcm2290: Replace test_ctl_hi1_val with test_ctl_hi_val  
**Upstream:** (none found)  
**Verdict:**  ❌ FAIL

### Reason
No lore.kernel.org link was found in the PR description or commit message(s).
This skill only validates patches against a lore.kernel.org source.

The commit has no vendor prefix (UPSTREAM:, FROMLIST:, BACKPORT:, QCLINUX:, PENDING:, WORKAROUND:) and no `Link:` or `Patch-mainline:` tag pointing to lore.kernel.org.

### Recommendation
Add a `Link: https://lore.kernel.org/r/<message-id>` line to the commit message and re-run validation, or use an appropriate prefix:

- **`UPSTREAM:`** → link to the merged kernel.org commit (not applicable here)
- **`FROMLIST:`** → link to the lore.kernel.org posting
- **`BACKPORT:`** → link to the original lore.kernel.org or upstream commit
- **`QCLINUX:`** → vendor-only change (no upstream link required)
- **`PENDING:`** → work-in-progress, not yet posted (no upstream link required)
- **`WORKAROUND:`** → temporary fix, not suitable for upstream (no upstream link required)

Commits with `QCLINUX:`, `PENDING:`, or `WORKAROUND:` prefixes have no upstream lore link by design and cannot be validated with this skill.

### Analysis
The patch corrects a typo in struct member names (`test_ctl_hi1_val` → `test_ctl_hi_val`) in three PLL configurations (GPLL8, GPLL10, GPLL11) in `drivers/clk/qcom/gcc-qcm2290.c`. This appears to be a bug fix that should either:

1. Be posted upstream to linux-clk mailing list (and tagged `FROMLIST:` with lore link), or
2. Be marked as `QCLINUX:` if it's a vendor-specific fix not intended for upstream

Without a lore link or vendor prefix, the commit's upstream status and intent cannot be determined.

### Final Summary
1. **Lore link present:** No — no lore.kernel.org link found in commit message
2. **Lore link matches PR commits:** N/A — no lore link to compare against
3. **Upstream patch status:** Unknown — cannot determine without lore link or vendor prefix
4. **PR present in qcom-next:** Not checked — filesystem permission restrictions prevented qcom-next clone/search


</details>
</blockquote>

**Comment by qlijarvis** [comment]
## PR #1479 — checker-log-analyzer

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1479
**Checker run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28857370311

| Checker | Result | Summary |
|---------|--------|---------|
| Checker | Result | Summary |
| checkpatch | ⚠️ | CI infrastructure failure - merge failed |
| dt-binding-check | ⚠️ | CI infrastructure failure - merge failed |
| dtb-check | ⚠️ | CI infrastructure failure - merge failed |
| sparse-check | ⚠️ | CI infrastructure failure - merge failed |
| check-uapi-headers | ⚠️ | CI infrastructure failure - merge failed |
| check-patch-compliance | ⚠️ | CI infrastructure failure - merge failed |
| tag-check | ❌ | Missing subject prefix (see below) |

Detailed report: [Full report](https://gist.github.com/qlijarvis/86850c7183761234660dd9b65a63f33d)

<blockquote>
<details>
<summary>Checker analysis — click to expand</summary>

## 🤖 CI Checker Analysis (checker-log-analyzer)

**PR:** #1479 - clk: qcom: gcc-qcm2290: Replace test_ctl_hi1_val with test_ctl_hi_val  
**Source:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28857370311

| Checker | Result | Summary |
|---------|--------|---------|
| checkpatch | ⚠️ | CI infrastructure failure - merge failed |
| dt-binding-check | ⚠️ | CI infrastructure failure - merge failed |
| dtb-check | ⚠️ | CI infrastructure failure - merge failed |
| sparse-check | ⚠️ | CI infrastructure failure - merge failed |
| check-uapi-headers | ⚠️ | CI infrastructure failure - merge failed |
| check-patch-compliance | ⚠️ | CI infrastructure failure - merge failed |
| tag-check | ❌ | Missing subject prefix (see below) |

---

### ⚠️ CI Infrastructure Failure — All Checkers

**Root cause:** Git merge operation failed with "refusing to merge unrelated histories" during the automerge/integration step that precedes all checker runs.

**Failure details:**
```
fatal: refusing to merge unrelated histories
Merge failed, manual merge
...
fatal: refusing to merge unrelated histories
Merge failed or conflicts detected. Aborting merge.
##[error]Process completed with exit code 3.
```

This error appeared identically in all six checker jobs:
- `checkpatch`
- `dt-binding-check`
- `dtb-check`
- `sparse-check`
- `check-uapi-headers`
- `check-patch-compliance`

**Analysis:**

The kernel-checkers CI workflow attempts to:
1. Create an integration branch based on the baseline (tag `19b282f417584cfe14ce6a262122c51553d026ec`)
2. Merge topic branches (starting with `topic/tech/bsp/clk`)
3. Merge the PR branch (`pr-1479`)

Both merge operations failed with "refusing to merge unrelated histories", which indicates that:
- The topic branch `topic/tech/bsp/clk` has no common ancestor with the baseline
- The PR branch `pr-1479` has no common ancestor with the integration branch

This is a **CI infrastructure/configuration issue**, not a defect in the patch itself.

**Fix:** 

This requires CI infrastructure remediation. Possible root causes:
1. The baseline tag or topic branch references are stale or incorrect
2. The PR branch was created from an incompatible base
3. The automerge configuration file is misconfigured

**Recommended actions:**
1. **Re-trigger the CI run** after verifying the PR branch is based on a valid integration point
2. **Verify the PR base branch** — ensure it's compatible with the kernel-checkers workflow
3. **Check the automerge configuration** — the topic branch `topic/tech/bsp/clk` may need to be removed or updated in the integration config

**Reproduce locally:**
```bash
# This cannot be reproduced as a patch issue — it's a CI workflow configuration problem
# To debug, inspect the automerge config and topic branch ancestry
```

---

### ❌ tag-check — Missing Subject Prefix

**Root cause:** The commit subject does not start with a required prefix tag.

**Failure details:**

Commit `2ddd3dc32bd48ea11ace0b93944beae2e86de8f7`:
```
Subject: clk: qcom: gcc-qcm2290: Replace test_ctl_hi1_val with test_ctl_hi_val
```

**Analysis:**

The commit subject lacks a mandatory prefix. All branches **except** `qcom-next` and `qcom-next-staging` require every commit to start with one of:
- `FROMLIST:` — Patch posted to mailing list (lore.kernel.org)
- `FROMGIT:` — Patch taken from a maintainer git tree
- `UPSTREAM:` — Patch merged into Linus's mainline tree
- `BACKPORT:` — Upstream patch backported with modifications
- `QCLINUX:` — Vendor-only change with no upstream equivalent
- `PENDING:` — Work-in-progress, not yet posted upstream
- `WORKAROUND:` — Temporary fix not suitable for upstream

**Note:** I could not definitively determine the target branch from the CI logs due to the merge failure. If the target branch is `qcom-next` or `qcom-next-staging`, this check does **not** apply and can be ignored.

**Fix:**

```bash
git rebase -i HEAD~1   # mark the commit as 'edit'
git commit --amend -m "FROMLIST: clk: qcom: gcc-qcm2290: Replace test_ctl_hi1_val with test_ctl_hi_val"
git rebase --continue
git push --force-with-lease
```

Choose the appropriate prefix based on the patch origin:
- If this patch has been posted to a mailing list → `FROMLIST:`
- If this patch is in a maintainer tree → `FROMGIT:`
- If this patch is merged into Linus's tree → `UPSTREAM:`
- If this is a vendor-only fix → `QCLINUX:`

---

### Verdict

**Cannot assess patch quality** — all checkers failed due to CI infrastructure issues before any code analysis could run.

**Immediate blockers:**
1. ❌ **CI infrastructure failure** — "refusing to merge unrelated histories" prevents all checker execution
2. ❌ **Missing subject prefix** — commit subject must start with a valid prefix tag (unless targeting `qcom-next` or `qcom-next-staging`)

**Recommended next steps:**
1. Fix the CI merge issue (likely requires maintainer intervention or PR rebase)
2. Add the appropriate subject prefix to the commit
3. Re-trigger the CI run after both fixes are applied

**Patch content assessment:** The actual code change (replacing `test_ctl_hi1_val` with `test_ctl_hi_val` in three locations) appears to be a straightforward bug fix correcting a typo in struct member names. This is likely a valid fix, but cannot be verified by CI until the infrastructure issues are resolved.


</details>
</blockquote>

**Comment by qcomlnxci** [comment]
@qualcomm-linux/kernel-topics This pull request has been marked as stale due to 30 days of inactivity and will automatically close after an additional 5 days.
