### PR TITLE
FROMLIST: arm64: dts: qcom: glymur: Enable LLCC/DDR/DDR_QOS DVFS

### PR DESCRIPTION
**Pull request by ppapaniy**
On Qualcomm Glymur SoCs, the memlat governor and the mechanism for controlling the LLCC and DDR/DDR_QOS frequencies run on the CPU Control Processor (CPUCP). Add the CPUCP mailbox and SCMI nodes required for the QCOM SCMI Generic Extension protocol to probe and get functional bus dvfs on Glymur/Mahua SoCs.

Link: https://lore.kernel.org/lkml/20260610-rfc_v7_scmi_memlat-v7-8-f3f68c608f25@oss.qualcomm.com/

### CODE REVIEW

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1471

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1471
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28663315959

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict | arch/arm64/boot/dts/qcom/glymur.dtsi | No | Topic branch `topic/tech/all/dt/glymur` has diverged from PR base; 101 total conflicts across the integration |

### Verdict
This is not a compilation error. The build failed during the integration merge phase when attempting to merge PR #1471 into topic branch `topic/tech/all/dt/glymur`. The PR itself does not introduce compilation errors; the failure is due to merge conflicts between the PR's base and the current state of the topic branch.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/6c3d654a96e420eea402413f08e7eae7)

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1471

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1471
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28663315959

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict (add/add) | `Documentation/devicetree/bindings/cpufreq/qcom,shikra-epss.yaml` | No | Pre-existing conflict in integration branch - both local and remote created the same file independently |
| 2 | Merge conflict (content) | `arch/arm64/boot/dts/qcom/glymur.dtsi` | Yes | PR modifies this file; conflicts with concurrent changes in base branch |
| 3 | Merge conflicts (content) | 99 other files | No | Pre-existing conflicts in integration branch unrelated to PR changes |

### Verdict
This is not a compilation failure. The build failed during the automerge/integration phase with 101 merge conflicts. Only 1 conflict (`arch/arm64/boot/dts/qcom/glymur.dtsi`) is directly related to this PR's changes; the remaining 100 conflicts are pre-existing integration issues in the base branch `tech/all/dt/glymur`.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/df495fca16a964110b05da333b21829f)

**Comment by qlijarvis** [comment]
## PR #1471 — validate-patch

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1471

| Verdict | Issues | Detailed Report |
|---------|--------|-----------------|
| N/A | 0 | [Full report](https://gist.github.com/qlijarvis/01b98506eba677a154600e968c0b8e96) |

### Final Summary
1. Lore link present: Not provided in agent output
2. Lore link matches PR commits: Not provided in agent output
3. Upstream patch status: Not provided in agent output
4. PR present in qcom-next: Not provided in agent output

<blockquote>
<details>
<summary>Verdict: N/A — click to expand</summary>

[/VALIDATE_PATCH_REPORT]
</details>
</blockquote>

**Comment by qlijarvis** [comment]
## PR #1471 — checker-log-analyzer

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1471
**Checker run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28663316009

| Checker | Result | Summary |
|---------|--------|---------|
| Checker | Result | Summary |
| checkpatch | ⏭️ | Not executed - merge failed |
| dt-binding-check | ⏭️ | Not executed - merge failed |
| dtb-check | ⏭️ | Not executed - merge failed |
| sparse-check | ⏭️ | Not executed - merge failed |
| check-uapi-headers | ⏭️ | Not executed - merge failed |
| check-patch-compliance | ⏭️ | Not executed - merge failed |
| tag-check | ✅ | Subject has valid `FROMLIST:` prefix |

Detailed report: [Full report](https://gist.github.com/qlijarvis/fe9aa8a02793185fa4bc239be709eb0b)

<blockquote>
<details>
<summary>Checker analysis — click to expand</summary>

## 🤖 CI Checker Analysis (checker-log-analyzer)

**PR:** #1471 - FROMLIST: arm64: dts: qcom: glymur: Enable LLCC/DDR/DDR_QOS DVFS  
**Source:** https://github.com/qualcomm-linux/kernel-config/actions/runs/28663316009  
**Target branch:** `tech/all/dt/glymur`

| Checker | Result | Summary |
|---------|--------|---------|
| checkpatch | ⏭️ | Not executed - merge failed |
| dt-binding-check | ⏭️ | Not executed - merge failed |
| dtb-check | ⏭️ | Not executed - merge failed |
| sparse-check | ⏭️ | Not executed - merge failed |
| check-uapi-headers | ⏭️ | Not executed - merge failed |
| check-patch-compliance | ⏭️ | Not executed - merge failed |
| tag-check | ✅ | Subject has valid `FROMLIST:` prefix |

---

### ❌ CI Infrastructure Failure — Merge Conflict

**Root cause:** The CI workflow failed during the automerge phase when attempting to merge the topic branch `topic/tech/all/dt/glymur` into the integration baseline. Git refused to merge due to unrelated histories.

**Failure details:**
```
Latest tag is 19b282f417584cfe14ce6a262122c51553d026ec
Create a new integration branch based on 19b282f417584cfe14ce6a262122c51553d026ec
Switched to a new branch 'integ'
Merging topic branches...
------------------------------------------
 ** Merging topic branch: topic/tech/all/dt/glymur
fatal: refusing to merge unrelated histories
Merge failed, manual merge
```

This error appeared identically across all six checker jobs:
- `checkpatch`
- `dt-binding-check`
- `dtb-check`
- `sparse-check`
- `check-uapi-headers`
- `check-patch-compliance`

**Analysis:**

The "refusing to merge unrelated histories" error occurs when Git detects that the two branches being merged do not share a common ancestor commit. This typically happens when:

1. **New topic branch with orphan commits** — The `tech/all/dt/glymur` topic branch was created with commits that have no shared history with the `qcom-next` baseline (SHA `19b282f417584cfe14ce6a262122c51553d026ec`).

2. **Branch initialization issue** — The topic branch may have been initialized from a different base or created as an orphan branch, making it incompatible with the standard automerge workflow.

3. **Baseline mismatch** — The integration baseline and the topic branch diverged from completely different starting points.

**Fix:**

This is **not a patch defect** — the patch content itself is valid (single commit adding SCMI/CPUCP nodes to `glymur.dtsi`). The issue is with the branch topology in the repository.

**Option 1: Rebase the topic branch onto the correct baseline**
```bash
# On the topic branch
git fetch origin qcom-next
git rebase origin/qcom-next
git push --force-with-lease origin tech/all/dt/glymur
```

**Option 2: Allow unrelated histories (if intentional)**
```bash
# In the automerge script, add --allow-unrelated-histories
git merge --no-ff --allow-unrelated-histories topic/tech/all/dt/glymur
```

**Option 3: Cherry-pick the commit onto a new branch**
```bash
# Create a new topic branch from the correct baseline
git checkout -b tech/all/dt/glymur-v2 19b282f417584cfe14ce6a262122c51553d026ec
git cherry-pick 3d693d70451854632bb185574fbbb82532deece7
git push origin tech/all/dt/glymur-v2
# Update PR to point to the new branch
```

**Recommended action:** Option 3 (cherry-pick) is the cleanest solution. It preserves the commit content while establishing proper ancestry with the integration baseline.

**Reproduce locally:**
```bash
git clone https://github.com/qualcomm-linux/kernel.git
cd kernel
git fetch origin qcom-next
git checkout -b integ 19b282f417584cfe14ce6a262122c51553d026ec
git fetch https://github.com/qualcomm-linux/kernel-topics.git tech/all/dt/glymur:topic/tech/all/dt/glymur
git merge --no-ff topic/tech/all/dt/glymur
# Will fail with: fatal: refusing to merge unrelated histories
```

---

### ✅ tag-check (Manual Review)

**Status:** PASS

The commit subject line starts with `FROMLIST:`, which is a valid prefix for patches posted to the upstream mailing list. The commit also includes a proper `Link:` trailer pointing to the lore.kernel.org thread:

```
Link: https://lore.kernel.org/lkml/20260610-rfc_v7_scmi_memlat-v7-8-f3f68c608f25@oss.qualcomm.com/
```

This satisfies the subject-prefix requirement for all branches except `qcom-next` and `qcom-next-staging`.

---

### Verdict

**CI failure is due to branch topology, not patch content.**

The patch itself appears valid:
- ✅ Proper `FROMLIST:` prefix
- ✅ Valid `Link:` trailer to upstream discussion
- ✅ Proper `Signed-off-by:` chain
- ✅ Clean devicetree additions (SCMI/CPUCP nodes for Glymur)

**Blocker:** The topic branch `tech/all/dt/glymur` has unrelated history and cannot be merged into the integration baseline. The branch needs to be rebased or the commit needs to be cherry-picked onto a properly-based branch.

**Next steps:**
1. Rebase `tech/all/dt/glymur` onto `qcom-next` baseline (SHA `19b282f417584cfe14ce6a262122c51553d026ec`), OR
2. Cherry-pick commit `3d693d70451854632bb185574fbbb82532deece7` onto a new topic branch with proper ancestry, OR
3. Contact the repository maintainer to investigate why the topic branch has orphan commits

Once the branch topology is fixed, re-trigger the CI run. The actual checker validations (checkpatch, dtb-check, etc.) were never executed due to the merge failure.


</details>
</blockquote>
