### PR TITLE
FROMLIST: arm64: dts: qcom: shikra: Switch CPU ETMs to MMIO-based probing

### PR DESCRIPTION
**Pull request by jiegan0107**
The etm0-etm3 nodes are declared with "arm,coresight-etm4x-sysreg" but do not implement self-hosted system-register trace access on this SoC: ID_AA64DFR0_EL1.TraceVer reads as 0 on the affected CPUs, so etm4_init_sysreg_access() correctly reports the access mechanism as unavailable and the ETMv4 driver fails to probe with -EINVAL.

The CPU ETMs have a memory-mapped aperture, so switch each node to the standard "arm,coresight-etm4x", "arm,primecell" compatible with its MMIO reg range.

Link: https://lore.kernel.org/all/20260922-fix-etm-probe-issue-on-shikra-v1-1-56d25e9bbe17@oss.qualcomm.com/
Fixes: eed738c6dd0c ("arm64: dts: qcom: shikra: Add coresight nodes")

CRs-Fixed: 4676018

### CODE REVIEW

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1871

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1871
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/35683191679

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict during automerge | arch/arm64/boot/dts/qcom/Makefile | No | Pre-existing integration conflict between topic/tech/all/shikra branch and baseline |
| 2 | Merge conflict during automerge | sound/soc/qcom/sc8280xp.c | No | Pre-existing integration conflict between topic/tech/all/shikra branch and baseline |

### Verdict
This is NOT a compilation failure. The build failed during the automerge/integration step due to 2 merge conflicts in files NOT modified by this PR. Both conflicts are pre-existing integration issues between the topic branch and the baseline, unrelated to the PR changes.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/7df397ed3c87170d0dcdb543f282b202)

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1871

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1871
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/35683191679

### Analysis Result: No Compilation Errors Found

This build did **not fail due to compilation errors**. The failure occurred during the **automerge/integration phase** before any compilation was attempted.

| Phase | Status | Details |
|-------|--------|---------|
| Automerge | ❌ Failed | Merge conflicts in 2 files during topic branch integration |
| Compilation | ⏭️ Skipped | Never reached due to automerge failure |

**Merge Conflicts Detected:**
1. `arch/arm64/boot/dts/qcom/Makefile` - conflict during merge with baseline
2. `sound/soc/qcom/sc8280xp.c` - conflict during merge with baseline

### Verdict
**Zero compilation errors.** The build failed during integration due to merge conflicts in files NOT modified by this PR. These are pre-existing integration issues between the topic branch (`topic/tech/all/shikra`) and the baseline branch, not introduced by PR #1871.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/8d97eea33f5fce7929ffbd7753d908f6)

**Comment by qlijarvis** [comment]
## PR #1871 — validate-patch

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1871

| Verdict | Issues | Detailed Report |
|---------|--------|-----------------|
| ⚠️ | 1 | [Full report](https://gist.github.com/qlijarvis/aeda10726c4720e82f582d807f93753b) |

### Final Summary
1. **Lore link present:** Yes — `https://lore.kernel.org/all/20260922-fix-etm-probe-issue-on-shikra-v1-1-56d25e9bbe17@oss.qualcomm.com/`
2. **Lore link matches PR commits:** Yes — diff content identical; line number shifts are context-only deltas due to tree state
3. **Upstream patch status:** ⏳ In review — posted Sep 22, 2026; Sashiko AI review comment received; author responded; no maintainer decision yet
4. PR present in qcom-next/topics: Partial - 1/1 commit(s) only have partial integration evidence

<blockquote>
<details>
<summary>Verdict: ⚠️ — click to expand</summary>

## 🔍 Patch Validation

**PR:** [#1871] FROMLIST: arm64: dts: qcom: shikra: Switch CPU ETMs to MMIO-based probing  
**Upstream commit:** https://lore.kernel.org/all/20260922-fix-etm-probe-issue-on-shikra-v1-1-56d25e9bbe17@oss.qualcomm.com/  
**Verdict:** ⚠️ PARTIAL

### Commit Message
| Check | Status | Note |
|-------|--------|------|
| Subject matches upstream | ✅ | `FROMLIST:` prefix added correctly |
| Body preserves rationale | ✅ | Technical explanation preserved |
| Fixes tag present/correct | ✅ | `Fixes: eed738c6dd0c` matches lore |
| Authorship preserved | ✅ | `FROMLIST:` allows submitter in `From:`; lore author present in `Signed-off-by:` |
| Backport note (if applicable) | N/A | Not a backport |
| Duplicate signature | ⚠️ | PR has extra `Signed-off-by: Jie Gan <jiegan@qti.qualcomm.com>` not in lore (different email domain) |

### Diff
| File | Status | Notes |
|------|--------|-------|
| `arch/arm64/boot/dts/qcom/shikra.dtsi:233` | ✅ | Context-only delta — line numbers differ (lore: 164, PR: 233) due to tree state; code identical |
| `arch/arm64/boot/dts/qcom/shikra.dtsi:4787` | ✅ | Context-only delta — line numbers differ (lore: 3150, PR: 4787) due to tree state; code identical |

### Issues
- **Duplicate Signed-off-by with different email**: PR contains `Signed-off-by: Jie Gan <jiegan@qti.qualcomm.com>` in addition to the lore author's `Signed-off-by: Jie Gan <jie.gan@oss.qualcomm.com>`. The lore patch only has the `@oss.qualcomm.com` signature. This is likely the author's internal email added during cherry-pick — acceptable but creates a duplicate signature for the same person.

### Verdict
**Merge with minor note**: Diff content faithfully represents the lore patch. Line number differences are due to tree state divergence (PR tree has additional nodes like `etm0-modem` not present in lore's base). The duplicate signature is a minor hygiene issue but does not affect correctness.

### Final Summary
1. **Lore link present:** Yes — `https://lore.kernel.org/all/20260922-fix-etm-probe-issue-on-shikra-v1-1-56d25e9bbe17@oss.qualcomm.com/`
2. **Lore link matches PR commits:** Yes — diff content identical; line number shifts are context-only deltas due to tree state
3. **Upstream patch status:** ⏳ In review — posted Sep 22, 2026; Sashiko AI review comment received; author responded; no maintainer decision yet
4. **PR present in qcom-next/topics:** Partial — integration_presence_report.md shows "partial - subject or partial tree evidence found, but full change was not verified"


### Deterministic Integration Presence

# Integration Presence Report

This report is generated by Jarvis before validate-patch runs.
It is the authoritative source for whether PR changes are already present
in qcom-next or in the kernel topic branches.

Kernel repo: `/local/mnt/workspace/sgaud/Qgenie/image_pipeline/kernel`
qcom-next ref: `56321f1b03c171fa3665a6f16a89f47a71a56dad`
topics remote: `topics` -> `https://github.com/qualcomm-linux/kernel-topics`
topics fetch: `fetched`

| Commit | Subject | qcom-next | topics | Final |
|--------|---------|-----------|--------|-------|
| 1/1 | `[PATCH] FROMLIST: arm64: dts: qcom: shikra: Switch CPU ETMs to` | partial - subject or partial tree evidence found, but full change was not verified | partial - subject or partial tree evidence found, but full change was not verified | partial |

## Final Status

overall_status: PARTIAL
present_commits: 0/1
partial_commits: 1/1
missing_commits: 0/1
topics_checked_for_commits: 1/1
final_summary: PR present in qcom-next/topics: Partial - 1/1 commit(s) only have partial integration evidence

</details>
</blockquote>

**Comment by qlijarvis** [comment]
## PR #1871 — checker-log-analyzer

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1871
**Checker run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/35683194207

| Checker | Result | Summary |
|---------|--------|---------|
| Checker | Result | Summary |
| checkpatch | ⏭️ | Skipped - automerge conflict |
| dt-binding-check | ⏭️ | Skipped - automerge conflict |
| dtb-check | ⏭️ | Skipped - automerge conflict |
| sparse-check | ⏭️ | Skipped - automerge conflict |
| check-uapi-headers | ⏭️ | Skipped - automerge conflict |
| check-patch-compliance | ⏭️ | Skipped - automerge conflict |
| tag-check | ✅ | PASS - commit has valid `FROMLIST:` prefix |

Detailed report: [Full report](https://gist.github.com/qlijarvis/136f97ea024b1b6c9a89cbae9253452c)

<blockquote>
<details>
<summary>Checker analysis — click to expand</summary>


## 🤖 CI Checker Analysis (checker-log-analyzer)

**PR:** #1871 - FROMLIST: arm64: dts: qcom: shikra: Switch CPU ETMs to MMIO-based probing  
**Source:** https://github.com/qualcomm-linux/kernel-config/actions/runs/35683194207

| Checker | Result | Summary |
|---------|--------|---------|
| checkpatch | ⏭️ | Skipped - automerge conflict |
| dt-binding-check | ⏭️ | Skipped - automerge conflict |
| dtb-check | ⏭️ | Skipped - automerge conflict |
| sparse-check | ⏭️ | Skipped - automerge conflict |
| check-uapi-headers | ⏭️ | Skipped - automerge conflict |
| check-patch-compliance | ⏭️ | Skipped - automerge conflict |
| tag-check | ✅ | PASS - commit has valid `FROMLIST:` prefix |

### ⚠️ CI Infrastructure Issue: Automerge Conflict

**Root cause:** The CI workflow failed during the automerge step before any checkers could run. The topic branch `topic/tech/all/shikra` has merge conflicts with the baseline integration branch.

**Failure details:**
```
Auto-merging arch/arm64/boot/dts/qcom/Makefile
CONFLICT (content): Merge conflict in arch/arm64/boot/dts/qcom/Makefile
Auto-merging sound/soc/qcom/common.c
Auto-merging sound/soc/qcom/sc8280xp.c
CONFLICT (content): Merge conflict in sound/soc/qcom/sc8280xp.c
Automatic merge failed; fix conflicts and then commit the result.
Merge failed, manual merge
automerge returned non-zero; check logs for conflicts
##[error]Process completed with exit code 1.
```

**Analysis:**

This is **not a patch defect**. The PR itself is clean:
- ✅ Single commit with proper `FROMLIST:` prefix
- ✅ Valid `Link:` trailer pointing to lore.kernel.org
- ✅ Proper `Fixes:` tag
- ✅ Signed-off-by present
- ✅ Only modifies DTS file (`arch/arm64/boot/dts/qcom/shikra.dtsi`)

The failure occurred because the kernel-checkers CI workflow attempts to merge all topic branches into an integration branch before running checks. The `topic/tech/all/shikra` branch has conflicts with other topic branches in:
1. `arch/arm64/boot/dts/qcom/Makefile` (likely new board additions)
2. `sound/soc/qcom/sc8280xp.c` (likely audio driver changes)

**These conflicts are unrelated to PR #1871's changes** — this PR only touches `shikra.dtsi`, not the Makefile or audio drivers.

**Fix:** 

**Option 1 (Recommended):** Resolve the topic branch conflicts in the integration tree:
```bash
# In the kernel-topics repo
git checkout topic/tech/all/shikra
git fetch origin
git rebase origin/qcom-next  # or the appropriate baseline
# Resolve conflicts in Makefile and sc8280xp.c
git push --force-with-lease
```

**Option 2:** Re-trigger CI after other conflicting PRs are merged:
- The conflicts may resolve themselves once other PRs touching the Makefile and audio drivers are merged first.
- Simply close and reopen the PR, or push a trivial update to trigger a new CI run.

**Option 3:** Run checkers locally on the PR commit directly (bypassing automerge):
```bash
git fetch origin pull/1871/head:pr1871
git checkout pr1871
./scripts/checkpatch.pl --strict --ignore FILE_PATH_CHANGES -g HEAD
# DT checks
make defconfig
make dt_binding_check
make CHECK_DTBS=y arch/arm64/boot/dts/qcom/shikra.dtb
```

### Verdict

**The PR patch itself is ready to merge** — it has proper formatting, valid prefix, upstream link, and only touches DTS. The CI failure is due to **topic branch integration conflicts unrelated to this PR's changes**. Resolve the automerge conflicts in the topic branch or wait for conflicting PRs to merge first, then re-trigger CI.


</details>
</blockquote>

**Review by Komal-Bajaj — APPROVED** [review]
