### PR TITLE
FROMLIST: Revert "clk: qcom: regmap-phy-mux: Rework the implementation"

### PR DESCRIPTION
**Pull request by qianyu-qcom**
This reverts commit e108373c54fbc844b7f541c6fd7ecb31772afd3c.

This has been reported to break PCIe on at least SM8350 and Eliza platforms. I had originally tested this on Hamoa (X1E) where there were no adverse effects. It's highly likely that this stems from a difference in how the bootloader configures the clocks.

Revert the offending change to fix the issue in the immediate, with the intent to revisit it in the upcoming cycle.

Reported-by: Dmitry Baryshkov <dmitry.baryshkov@oss.qualcomm.com>
Reported-by: Abel Vesa <abel.vesa@oss.qualcomm.com>

Fixes: e108373c54fb ("clk: qcom: regmap-phy-mux: Rework the implementation")
Closes: https://lore.kernel.org/all/c675lcfptr4xgg4hcjp66unmuozgsvgwvtymh7on6jcipjrdw7@jy4h7fkwqwjg/
Reviewed-by: Dmitry Baryshkov <dmitry.baryshkov@oss.qualcomm.com>

### CODE REVIEW

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1530

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1530
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/29732876009

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict | `drivers/clk/qcom/tcsrcc-glymur.c` | No | Pre-existing conflict in topic branch when merging with baseline |
| 2 | Merge conflict | `drivers/clk/qcom/tcsrcc-x1e80100.c` | No | Pre-existing conflict in topic branch when merging with baseline |

### Verdict
**0 of 2 errors are introduced by this PR; both are pre-existing integration conflicts in the topic branch.**

The build failure is **NOT caused by PR #1530**. The PR only modifies `drivers/clk/qcom/clk-regmap-phy-mux.c` (a revert of a previous change), but the merge conflicts occur in completely different files (`tcsrcc-glymur.c` and `tcsrcc-x1e80100.c`) when the CI attempts to merge the entire `topic/tech/bsp/clk` branch into the integration baseline. These conflicts exist independently of this PR and indicate that other commits in the topic branch conflict with the baseline.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/8bd96a0d7904e80fa0956d547cb0c720)

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1530

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1530
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/29732876009

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict | `drivers/clk/qcom/tcsrcc-glymur.c` | No | Pre-existing integration conflict - unrelated to PR changes |
| 2 | Merge conflict | `drivers/clk/qcom/tcsrcc-x1e80100.c` | No | Pre-existing integration conflict - unrelated to PR changes |

### Verdict
**No compilation errors found.** The build failed during the integration/merge phase with conflicts in files that are NOT modified by this PR. Both conflicts are pre-existing integration issues unrelated to the PR changes in `drivers/clk/qcom/clk-regmap-phy-mux.c`.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/dcc2466cf1ce54bef6f93008d167f552)

**Comment by qlijarvis** [comment]
## PR #1530 — validate-patch

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1530

| Verdict | Issues | Detailed Report |
|---------|--------|-----------------|
| ❌ | 0 | [Full report](https://gist.github.com/qlijarvis/956e405425aa4c562a1fb3f833dbfecc) |

### Final Summary
1. **Lore link present:** No — `Closes:` tag points to a bug report thread, but no `Link:` tag pointing to the patch posting itself
2. **Lore link matches PR commits:** N/A — cannot validate without the patch posting Link: tag
3. **Upstream patch status:** Unknown — cannot determine without the patch posting Link: tag
4. PR present in qcom-next/topics: Yes - all 1 commit(s) are present in qcom-next or topics

<blockquote>
<details>
<summary>Verdict: ❌ — click to expand</summary>

## 🔍 Patch Validation

**PR:** #1530 - FROMLIST: Revert "clk: qcom: regmap-phy-mux: Rework the implementation"
**Upstream commit:** N/A (no Link: tag found)
**Verdict:** ❌ FAIL

### Commit Message
| Check | Status | Note |
|-------|--------|------|
| Subject matches upstream | ⚠️ | Cannot verify - no lore Link: tag present |
| Body preserves rationale | ⚠️ | Cannot verify - no lore Link: tag present |
| Fixes tag present/correct | ✅ | Fixes: e108373c54fb present and correctly formatted |
| Authorship preserved | ⚠️ | FROMLIST: submitter (Qiang Yu) differs from author (Konrad Dybcio); original author's Signed-off-by is present - this is correct for FROMLIST |
| Backport note (if applicable) | N/A | Not a backport |

### Diff
| File | Status | Notes |
|------|--------|-------|
| drivers/clk/qcom/clk-regmap-phy-mux.c | ⚠️ | Cannot verify against upstream - no lore Link: tag |

### Issues

**Critical:**
1. **Missing Link: tag** — FROMLIST: commits must include a `Link: https://lore.kernel.org/r/<message-id>` tag pointing to the upstream posting. The commit has a `Closes:` tag pointing to a lore thread, but this is not the canonical patch posting link.

**Observations:**
2. **Authorship is correct for FROMLIST** — The submitter (Qiang Yu) appears in the final `Signed-off-by:` and `From:` fields, while the original author (Konrad Dybcio) is preserved in the first `Signed-off-by:`. This follows the correct FROMLIST pattern.
3. **Closes: tag present** — Points to `https://lore.kernel.org/all/c675lcfptr4xgg4hcjp66unmuozgsvgwvtymh7on6jcipjrdw7@jy4h7fkwqwjg/` but this appears to be a bug report thread, not the patch posting itself.

### Verdict

**Do not merge without correction.** The commit is missing the mandatory `Link:` tag that points to the canonical lore.kernel.org patch posting. For FROMLIST: commits, this tag is required to enable validation of the patch content against the upstream source.

**Required fix:** Add a `Link: https://lore.kernel.org/r/<message-id>` line pointing to the actual patch posting on lore.kernel.org (not the bug report thread). The Link: tag should appear after the commit body and before the trailers section.

### Final Summary
1. **Lore link present:** No — `Closes:` tag points to a bug report thread, but no `Link:` tag pointing to the patch posting itself
2. **Lore link matches PR commits:** N/A — cannot validate without the patch posting Link: tag
3. **Upstream patch status:** Unknown — cannot determine without the patch posting Link: tag
4. **PR present in qcom-next/topics:** Yes — exact patch-id match found at `0aec16a93bac6b2db928119bd34cc1e896173af4` in topics (per integration_presence_report.md)


### Deterministic Integration Presence

# Integration Presence Report

This report is generated by Jarvis before validate-patch runs.
It is the authoritative source for whether PR changes are already present
in qcom-next or in the kernel topic branches.

Kernel repo: `/local/mnt/workspace/sgaud/Qgenie/image_pipeline/kernel`
qcom-next ref: `a5cf3debd8c3c660711ad586ad4bb84e9ca42635`
topics remote: `topics` -> `https://github.com/qualcomm-linux/kernel-topics`
topics fetch: `fetched`

| Commit | Subject | qcom-next | topics | Final |
|--------|---------|-----------|--------|-------|
| 1/1 | `[PATCH] FROMLIST: Revert "clk: qcom: regmap-phy-mux: Rework the` | partial - subject or partial tree evidence found, but full change was not verified | present - exact patch-id match at 0aec16a93bac6b2db928119bd34cc1e896173af4 | present |

## Final Status

overall_status: PASS
present_commits: 1/1
partial_commits: 0/1
missing_commits: 0/1
topics_checked_for_commits: 1/1
final_summary: PR present in qcom-next/topics: Yes - all 1 commit(s) are present in qcom-next or topics

</details>
</blockquote>

**Comment by qlijarvis** [comment]
## PR #1530 — checker-log-analyzer

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1530
**Checker run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/29732875902

| Checker | Result | Summary |
|---------|--------|---------|
| Checker | Result | Summary |
| checkpatch | ⚠️ | CI infrastructure failure - merge error |
| dt-binding-check | ⚠️ | CI infrastructure failure - merge error |
| dtb-check | ⚠️ | CI infrastructure failure - merge error |
| sparse-check | ⚠️ | CI infrastructure failure - merge error |
| check-uapi-headers | ⚠️ | CI infrastructure failure - merge error |
| check-patch-compliance | ⚠️ | CI infrastructure failure - merge error |
| tag-check | ✅ | Subject has valid `FROMLIST:` prefix |
| qcom-next-check | ⚠️ | Missing `Link:` tag (has `Closes:` instead) |

Detailed report: [Full report](https://gist.github.com/qlijarvis/00bc78a6b1fce2318de326a271eeabb5)

<blockquote>
<details>
<summary>Checker analysis — click to expand</summary>


## 🤖 CI Checker Analysis (checker-log-analyzer)

**PR:** #1530 - FROMLIST: Revert "clk: qcom: regmap-phy-mux: Rework the implementation"  
**Source:** https://github.com/qualcomm-linux/kernel-config/actions/runs/29732875902

| Checker | Result | Summary |
|---------|--------|---------|
| checkpatch | ⚠️ | CI infrastructure failure - merge error |
| dt-binding-check | ⚠️ | CI infrastructure failure - merge error |
| dtb-check | ⚠️ | CI infrastructure failure - merge error |
| sparse-check | ⚠️ | CI infrastructure failure - merge error |
| check-uapi-headers | ⚠️ | CI infrastructure failure - merge error |
| check-patch-compliance | ⚠️ | CI infrastructure failure - merge error |
| tag-check | ✅ | Subject has valid `FROMLIST:` prefix |
| qcom-next-check | ⚠️ | Missing `Link:` tag (has `Closes:` instead) |

---

### ⚠️ CI Infrastructure Failure

**Root cause:** All checker jobs failed during the merge phase with "fatal: refusing to merge unrelated histories" when attempting to merge PR #1530 into the integration branch.

**Failure details:**
```
2026-07-20T10:06:59.6257752Z Fetching PR #1530 from https://github.com/qualcomm-linux/kernel-topics.git...
2026-07-20T10:07:00.2734866Z From https://github.com/qualcomm-linux/kernel-topics
2026-07-20T10:07:00.2735481Z  * [new ref]                   refs/pull/1530/head -> pr-1530
2026-07-20T10:07:00.2925831Z Merging pr-1530 (no-commit)...
2026-07-20T10:07:20.4337466Z fatal: refusing to merge unrelated histories
2026-07-20T10:07:20.5495925Z Merge failed or conflicts detected. Aborting merge.
2026-07-20T10:07:20.5514404Z fatal: There is no merge to abort (MERGE_HEAD missing).
2026-07-20T10:07:20.5531943Z ##[error]Process completed with exit code 3.
```

**Analysis:** This is a CI infrastructure/configuration issue, not a patch quality problem. The error "refusing to merge unrelated histories" indicates that the PR branch and the integration baseline (`a5cf3debd8c3c660711ad586ad4bb84e9ca42635`) do not share a common ancestor in Git history. This typically occurs when:

1. The PR branch was created from a different repository or baseline
2. The topic branch (`topic/tech/bsp/clk`) has an incompatible history
3. The CI merge strategy needs `--allow-unrelated-histories` flag

**Fix:** This requires CI infrastructure changes or repository configuration fixes:
- Re-trigger the CI run after verifying the PR branch is based on a compatible baseline
- Contact the repository maintainers to investigate the branch history mismatch
- The PR author may need to rebase the PR onto the correct baseline

**No patch changes needed** — the patch content itself is not the issue.

---

### ⚠️ check-patch-compliance — Missing Link: Tag

**Root cause:** The commit uses `Closes:` tag instead of `Link:` tag for the lore.kernel.org reference.

**Failure details:**
```
Subject: [PATCH] FROMLIST: Revert "clk: qcom: regmap-phy-mux: Rework the implementation"
...
Closes: https://lore.kernel.org/all/c675lcfptr4xgg4hcjp66unmuozgsvgwvtymh7on6jcipjrdw7@jy4h7fkwqwjg/
```

**Analysis:** The `check-patch-compliance` checker expects a `Link:` tag pointing to the upstream lore.kernel.org patch. While `Closes:` is a valid tag for referencing bug reports or discussions, `FROMLIST:` commits should include a `Link:` tag pointing to the actual patch submission on lore.

**Fix:** Add a `Link:` tag to the commit message pointing to the lore.kernel.org patch URL:

```bash
git rebase -i <base_sha>   # mark commit as 'edit'
git commit --amend
# Add this line to the commit message body (before Signed-off-by):
# Link: https://lore.kernel.org/all/<message-id>/
git rebase --continue
```

**Note:** The `Closes:` tag can remain — it references the bug report thread. The `Link:` tag should point to the actual patch submission (the revert patch posted to the mailing list).

**Reproduce locally:**
```bash
# Verify the lore link exists for the patch
b4 am --single-message -C -l -3 <lore-patch-url>
```

---

### ✅ tag-check — PASS

**Analysis:** The commit subject correctly starts with `FROMLIST:`, which is a valid prefix for patches posted to the mailing list. The subject format is correct:

```
FROMLIST: Revert "clk: qcom: regmap-phy-mux: Rework the implementation"
```

This satisfies the subject-prefix requirement for all branches except `qcom-next` and `qcom-next-staging`.

---

### Verdict

**CI infrastructure failure prevents checker execution.** The patch content appears well-formed with proper `FROMLIST:` prefix, but requires:

1. **Blocker:** CI infrastructure fix to resolve "unrelated histories" merge error — requires maintainer intervention
2. **Recommended:** Add `Link:` tag pointing to the lore.kernel.org patch submission to satisfy `check-patch-compliance`

**Action required:** Re-trigger CI after repository/branch configuration is fixed. Optionally add `Link:` tag to improve compliance.


</details>
</blockquote>
