### PR TITLE
FROMLIST: arm64: dts: qcom: hamoa-pmics: Add ADC support

### PR DESCRIPTION
**Pull request by raryan-qcom**
Add ADC node and define channels for:
- Die temperature for PMK8550, PM8550VE* and PMC8380* PMICs.
- PM8550: Die temperature, VPH power, and system thermistors.

Define thermal zones 'sys-0-thermal' through 'sys-6-thermal' which correspond to the off-PMIC system thermistors connected via PM8550 AMUX/GPIO lines.

Also,add io-channels and io-channel-names properties to the temp_alarm nodes so that they can get temperature reading from the ADC die_temp channels.

Link: https://lore.kernel.org/all/20260614-adc5_gen3_dt-v2-4-32ec576c5865@oss.qualcomm.com/

CRs-Fixed: 4559466

### CODE REVIEW

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1375

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1375
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/27744792368

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict during automerge | drivers/thermal/qcom/Kconfig | No | Pre-existing conflict in topic branch `topic/tech/pmic/misc` when merging with baseline |
| 2 | Merge conflict during automerge | drivers/thermal/qcom/Makefile | No | Pre-existing conflict in topic branch `topic/tech/pmic/misc` when merging with baseline |

### Verdict
**No compilation errors exist.** The build failed during the pre-build automerge/integration phase due to merge conflicts in files unrelated to this PR. Both conflicts are pre-existing issues in the topic branch, not introduced by PR #1375.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/536dea53583ec9edee9c35fc92e149ad)

**Comment by qlijarvis** [comment]
## 🔨 Build Failure Analysis — PR #1375

**PR:** https://github.com/qualcomm-linux/kernel-topics/pull/1375
**Build run:** https://github.com/qualcomm-linux/kernel-config/actions/runs/27744792368

| # | Error | File:Line | PR-introduced? | Root Cause |
|---|-------|-----------|----------------|------------|
| 1 | Merge conflict during integration | `drivers/thermal/qcom/Kconfig` | No | Pre-existing conflict between topic branch and baseline; PR only modifies DTS file |
| 2 | Merge conflict during integration | `drivers/thermal/qcom/Makefile` | No | Pre-existing conflict between topic branch and baseline; PR only modifies DTS file |

### Verdict
**No compilation errors occurred.** The build failed during the merge/integration phase with conflicts in `drivers/thermal/qcom/Kconfig` and `drivers/thermal/qcom/Makefile`. These conflicts are **not introduced by this PR** — the PR only modifies `arch/arm64/boot/dts/qcom/hamoa-pmics.dtsi`. The conflicts exist between other commits in the topic branch (`topic/tech/pmic/misc`) and the baseline integration branch.

📎 **Detailed analysis:** [Full report](https://gist.github.com/qlijarvis/2012215b2d36d3a78268095f408bc66b)
